# Generated by Django 2.1.7 on 2019-04-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('major', models.TextField()),
                ('grade', models.IntegerField()),
                ('hometown', models.TextField()),
            ],
        ),
    ]
